
name: Test-CI

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


jobs: 
  test:
    name: test 

    runs-on: ubuntu-latest
    
    steps:

      - name: install httpd
        run: |
          sudo apt update
          sudo apt install apache2
          echo "Hello World"

      - name: curl
        run: curl -L http://www.google.com      

